import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { CanonicalInvoice } from "@invex/core";
import type { LiteralInvoiceDoc } from "./literal/spec";
import { layoutInvoice, type LayoutOptions, type PageLayout } from "./layout/invoiceLayout";
import { renderDoclingJson } from "./render/toDoclingJson";
import { renderOcrDoclingJson } from "./render/toOcrDoclingJson";
import { renderPdf } from "./render/toPdf";

/**
 * Golden scenarios — the oracle.
 *
 * Each file carries two INDEPENDENTLY authored halves:
 *   render.doc          what is printed on the page, as literal strings
 *   expected.canonical  the CanonicalInvoice a competent human reading that
 *                       page would type
 *
 * Neither is computed from the other, and neither is computed at all. The
 * pipeline is the only thing that claims to connect them. Contrast the previous
 * arrangement, where out/expected.json was regenerated by the same
 * computeInvoice() that rendered the PDFs — a suite that validated the pipeline
 * against its own arithmetic and could not fail for the right reason.
 *
 * `reviewed: false` marks a DRAFT produced by `pnpm fixtures:label` from the
 * pipeline's own output. A draft may not be used as an expectation until a
 * human has checked it — enforced by goldenPurity.test.ts.
 */

export interface GoldenSmoke {
  route?: "zugferd" | "text" | "image";
  terminalStatus?: string;
  /** Trace events that must appear somewhere in the document's history. */
  hasEvents?: string[];
  /** Trace events that must NOT appear — e.g. proving the GPU stayed cold. */
  notEvents?: string[];
}

export interface Golden {
  id: string;
  title: string;
  /** false = machine-drafted, not yet human-checked. Never an expectation. */
  reviewed: boolean;
  authoredOn: string;
  layout?: LayoutOptions;
  /**
   * An INVEX id when the pipeline does NOT yet produce `expected` for this
   * scenario. The golden keeps stating the truth; the pipeline test turns the
   * assertion into an it.fails() pin, so it goes red the day the defect is
   * fixed. Recording current-but-wrong behaviour in the oracle instead would
   * re-create exactly the circularity this corpus exists to remove.
   */
  knownBug?: string;
  /**
   * Synthetic scenarios carry a literal page we can render. Scenarios drafted
   * from a REAL PDF by `pnpm fixtures:label` cannot — the PDF itself is the
   * source — so they carry `source` instead.
   */
  render?: { doc: LiteralInvoiceDoc };
  source?: { pdfFile: string; documentId?: string; pipelineStatus?: string; note?: string };
  /** Pipeline output awaiting human correction. Never an expectation. */
  draftCanonical?: unknown;
  expected: {
    /** null for documents that are not invoices. */
    canonical: CanonicalInvoice | null;
    smoke?: GoldenSmoke;
  };
}

const HERE = dirname(fileURLToPath(import.meta.url));
export const SCENARIOS_DIR = join(HERE, "..", "scenarios");

export function loadGoldens(): Golden[] {
  return readdirSync(SCENARIOS_DIR)
    .filter((f) => f.endsWith(".golden.json"))
    .sort()
    .map((f) => JSON.parse(readFileSync(join(SCENARIOS_DIR, f), "utf8")) as Golden);
}

export function loadGolden(id: string): Golden {
  const found = loadGoldens().find((g) => g.id === id);
  if (!found) throw new Error(`no golden scenario with id ${JSON.stringify(id)}`);
  return found;
}

/** Synthetic goldens only — a real-PDF scenario has no literal page to lay out. */
export function isSynthetic(g: Golden): g is Golden & { render: { doc: LiteralInvoiceDoc } } {
  return g.render?.doc !== undefined;
}

export function layoutOf(g: Golden): PageLayout[] {
  if (!isSynthetic(g)) {
    throw new Error(`golden ${g.id} was drafted from a real PDF (${g.source?.pdfFile}) and cannot be laid out`);
  }
  return layoutInvoice(g.render.doc, g.layout ?? {});
}

/** Born-digital PDF with a real text layer (Path B / triage `text`). */
export function goldenPdf(g: Golden): Promise<Uint8Array> {
  return renderPdf(layoutOf(g));
}

/** DoclingDocument JSON as Path B would receive it. */
export function goldenDocling(g: Golden, opts?: Parameters<typeof renderDoclingJson>[1]): unknown {
  return renderDoclingJson(layoutOf(g), opts);
}

/** Word-level, table-free DoclingDocument JSON as Path C would receive it. */
export function goldenOcrDocling(g: Golden, opts?: Parameters<typeof renderOcrDoclingJson>[1]): unknown {
  return renderOcrDoclingJson(layoutOf(g), opts);
}
